Feature/contact
Korobass87/team-project pull request #7
Opened 2021-10-23 19:07 UTC by OlgaSedovaNN

2021-10-23 20:35 UTC, Korobass87 requested changes

2021-10-23 20:35 UTC, Korobass87 commented on src/partials/contact.html
> +        <button class="contact__btn">Send</button>
тут надо прописать type для кнопки, type=submit для форм используем

2021-10-23 20:35 UTC, Korobass87 commented on src/partials/contact.html
> +        <button class="contact__btn">Send</button>
и чтобы не дергаться уже со стилями для кнопки, сделай при ховере и фокусе background-color: #aa6543;

2021-10-24 07:45 UTC, OlgaSedovaNN commented on src/partials/contact.html
> +        <button class="contact__btn">Send</button>
исправлено

2021-10-24 11:12 UTC, Korobass87 approved these changes

2021-10-24 11:12 UTC, Korobass87 commented on src/partials/contact.html
> +<div class="container">
поменяй местами секцию и контейнер

2021-10-24 11:12 UTC, Korobass87 commented on src/sass/_contact.scss
> +.contact {
нет стилей для контейнера, договорились сделать для него ширины

2021-10-24 11:12 UTC, Korobass87 commented on src/sass/_contact.scss
> +  border: none;
задай пожалуйста background для инпутов, а то они стандартные белые, а фон желтоватый

2021-10-24 11:13 UTC, merged